### ISSUE TITLE
Incorrect use assignable_users

### ISSUE THREAD

**Issue by kvetkin** [rgtk/redmine_editauthor#1]
When I change author, I am not see some users, because it role can create new issues, but issue can't be assign to this role.
Please, fix it, change assignable_users to other rule.

**Comment by rgtk** [comment]
You are right,

**Comment by nounder** [comment]
Please download most recent version 0.9.1 and check it out. Now every user that can add issue can be candidate for author change.

Thanks.

**Comment by kvetkin** [comment]
Thanks a lot. It working fine.
