### ISSUE TITLE
Slow loading time

### ISSUE THREAD

**Issue by nounder** [rgtk/redmine_editauthor#19]
Plugin currently uses `User#allowed_to?` to find and filter possible authors. This is slow because Redmine internally fetches all roles and memberships for each user to know if necessary permission is granted.

**Comment by nounder** [comment]
@yoshida3669, referring to your #15 PR:

I created a branch with changes that should resolve your case. I rewrote Redmine mechanism for traversing permissions. Instead of 5 queries, now plugin send only 2 that are easy to cache for database. You can see changes and download it here: https://github.com/rgtk/redmine_editauthor/tree/performance

Please let me know about the results when you test it.

**Comment by yoshida3669** [comment]
@rgtk Thank you for your amazing work!
Before your fix, our redmine become slower 10 seconds with your plugin.
But after your fix, it costs only 0.3 seconds! 👍

**Comment by nounder** [comment]
Enjoy!
