### ISSUE TITLE
Author not in group

### ISSUE THREAD

**Issue by kalvaer** [rgtk/redmine_editauthor#2]
If an original author is registered in redmine, however not listed in the group for which the project is running, when you update the ticket, it automatically selects another user and changes the author.

This is also not the first person on the list, however it appears to be the same one each time.

Is it possible to also sort the list in alphabetical order.

Cheers

**Comment by nounder** [comment]
@yoshida3669 fixed it with Pull Request #3. It is merged now. You can now download recent version. Enjoy!
