### ISSUE TITLE
Author not editable when creating Ticket

### ISSUE THREAD

**Issue by SkunkerAG** [rgtk/redmine_editauthor#26]
Hello,
we are doing telephone tickets, so it would be a help if the author would be editable when creating tickets.
thank you.

---
Environment:
  Redmine version                3.2.1.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  advanced_roadmap               0.10.1
  issue_charts                   1.3.0
  localizable                    0.4.0
  quick_view                     0.3.0
  redmine_agile                  1.4.1
  redmine_didyoumean             1.2.0
  redmine_editauthor             0.9.0
  redmine_issue_badge            0.0.3
  redmine_issues_tree            0.0.9
  redmine_ldap_sync              2.0.8.devel
  redmine_lightbox2              0.2.7
  redmine_my_page                0.1.10
  redmine_people                 1.2.0
  redmine_tags                   3.1.1
  redmine_theme_changer          0.2.0

**Comment by nounder** [comment]
Grant "Set original author" permission to set issue author on creation.

**Comment by SkunkerAG** [comment]
we need to perform an update, sorry, great work!

**Comment by nounder** [comment]
Enjoy!
