### ISSUE TITLE
Redmine 4.0

### ISSUE THREAD

**Issue by hyperized** [rgtk/redmine_editauthor#34]
Hi,

Is there any way this plugin can be made to work with Redmine 4.0?

**Comment by nounder** [comment]
What happens if you run it with Redmine 4.0?

**Comment by hyperized** [comment]
To be fair, we haven't tried due to the compability being only listed up to 3.4 (https://www.redmine.org/plugins/redmine_editauthor). If you suspect it'll work just fine, I can install and see :).

**Comment by hyperized** [comment]
Oh, well I tried and can confirm it works on 4.0 :).
