### ISSUE TITLE
Actual issue author is hidden

### ISSUE THREAD

**Issue by MEschenbacher** [rgtk/redmine_editauthor#41]
Hey,

great plugin, it is working very well!

We've noticed that we have no way of retrieving the actual issue author within the redmine webinterface. I'm assuming this is intended behavour. Isn't it?

Do you think it is desirable to create a journal entry which reflects the actual creator of the issue and changes it to the dropdown-selected author?

BR Max

**Comment by nounder** [comment]
Max,

When author is changed the journal entry [is added](https://github.com/sojitko/redmine_editauthor/blob/4f5fcc6068e37c35d2104ac4af2e3b83747bf93d/lib/redmine_editauthor/hook.rb#L46).

Doesn't it work on your instance?

**Comment by MEschenbacher** [comment]
Hey,

changing authors works fine and we see the journal entry.

I'm talking about the issue creation: Upon issue creation, there is no way of knowing if the issue author is the actual author or if he was selected by another user.

Think of it as some kind of paper trail: One might want to know if the ticket was actually created by this user in the author field or created on behalf of the user.

**Comment by nounder** [comment]
We could create journal entry when creating an issue if author is different than current user. This should be customisable in settings.

I will gladly review Pull Requests for this.
