### ISSUE TITLE
Empty combo

### ISSUE THREAD

**Issue by Nepomuk3000** [rgtk/redmine_editauthor#7]
Hi, 
As manager on my redmine database, I checked the "Edit issue autor" in the role configuration. Thus all permissions are given for the manager role. 
The result is a new combo box "Auteur" on the editing issue page. 
Unfortunately the combo is empty. 

The issue was seen on :
French interface 
Redmine 2.3.1.stable
Ruby 2.0.0 (i686-linux} 
Rails 3.2.13
Environment production 
Database adapter Mysql2
redmine_editauthor 0.9.1

Moreover, because of my company information system, public plugin directory is in read only mode

**Comment by nounder** [comment]
Can you please test version 0.9.4 that was released 2 days ago? Your problem seems related to #2 which is now fixed.

**Comment by Nepomuk3000** [comment]
Thank you for this very fast reply. 
I now have a combo filled but only with the initial author.

**Comment by nounder** [comment]
That is interesting. Combobox should be populated with active members of current project that has "Add issues" permission.

How many users are member of the project in which you try to change author of the issue? Do they comply to criteria mentioned above?

**Comment by Nepomuk3000** [comment]
My mistake, I moved the issues to a new sub project without adding members.
Now it works very well and will be extremely useful. Thanks a lot

**Comment by nounder** [comment]
Glad I could help. Enjoy this piece of code!
