### ISSUE TITLE
Choose Author on new Issue creation

### ISSUE THREAD

**Issue by sgargel** [rgtk/redmine_editauthor#8]
It would be greatly appreciated if the plugin allow you to choose the Author when creating a new Issue. Is it possible?

**Comment by nounder** [comment]
I would be interested in implementing this but I don't see much use of it. Can you share any use case for that?

**Comment by Nepomuk3000** [comment]
I was about to ask this too.... My use case is : I have a tracker Action. I attend a meeting and have to write the record. When I insert the action given during the meeting I now have to insert it as the author even if it is another attender who demanded it and change it just after.

**Comment by sgargel** [comment]
My use case is: Using a project for helpdesk happens that I've to open a issue for a customer calling me by phone. I insert new issue and suddenly change the author from myself to customer registered user that will be notified, etc..

**Comment by nounder** [comment]
@sgargel You can use [redmine_shady](https://github.com/rgtk/redmine_shady) plugin that will allow you to temporarily disable any notification triggered by your changes with a click of a button.

**Comment by sgargel** [comment]
Sorry, I've not explained well. My problem is that in 99% of case i'm changing author of issue as first action because i'm opening on behalf of the real author and I already know who is.
Now I have to do this in two steps...

**Comment by nounder** [comment]
Implemented in version 0.10.0. To avoid confusion and misuse, additional "Set original author" permission must be granted for this functionality.
